version: '3.8'


networks:
  tutorial-tier:
    driver: bridge


services:
  zookeeper:
    container_name: zookeeper_one
    image: 'bitnami/zookeeper:latest'
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - tutorial-tier
    ports:
      - '2181:2181'

  kafka:
    container_name: kafka_one
    image: 'bitnami/kafka:latest'
    restart: always
    depends_on:
      - zookeeper
    networks:
      - tutorial-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
